# base image
FROM ubuntu:latest

# nginx install
RUN apt -y update && apt -y upgrade
RUN apt -y install nginx

# port 
EXPOSE 80

# server exeecution
CMD ["nginx","-g","daemon off"]# base image
FROM ubuntu:latest

# nginx install
RUN apt -y update && apt -y upgrade
RUN apt -y install nginx

# port 
EXPOSE 80

# server exeecution
CMD ["nginx","-g","daemon off"]# base image
FROM ubuntu:latest

# nginx install
RUN apt -y update && apt -y upgrade
RUN apt -y install nginx

# port 
EXPOSE 80

# server exeecution
CMD ["nginx","-g","daemon off"]
